server:
  port: 9013
spring:
  application:
    name: aepc-api-spring-secur-oauth2-kafka-avro-bs-ms-company
  datasource:
    url: jdbc:postgresql://localhost:5432/companies-db?createDatabaseIfNotExist=true
