server:
  port: 9012
spring:
  application:
    name: aepc-api-spring-secur-oauth2-kafka-avro-bs-ms-address
  datasource:
    url: jdbc:postgresql://localhost:5432/addresses-db
    username: admin
    password: admin123 
  jpa: 
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect        
