server:
  port: 9010
spring:
  application:
    name: aepc-api-gateway-service
  # to indicate where services registration is running on
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/ # this is docker image of regsitraion service
         
