server:
  port: 9014
spring:
  application:
    name: aepc-api-spring-secur-oauth2-kafka-avro-bs-ms-employee
  datasource:
    url: jdbc:mysql://localhost:3306/employees-db?createDatabaseIfNotExist=true
