server:
  port: 9014
spring:
  application:
aepc-api-spring-secur-oauth2-kafka-bs-ms-employee
  datasource:
    url: jdbc:mysql://localhost:3306/employees-db?createDatabaseIfNotExist=true
# to indicate where services registration is running on
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/ # this is docker image of regsitraion service
