server:
  port: 9013
spring:
  application:
    name: aepc-api-spring-secur-oauth2-kafka-avro-bs-ms-company
  datasource:
    url: jdbc:mysql://localhost:3306/companies-db?createDatabaseIfNotExist=true
# to indicate where services registration is running on
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/ # this is docker image of regsitraion service
